apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-ingress-cert
  namespace: istio-system
spec:
  secretName: client-ingress-cert
  issuerRef:
    name: letsencrypt-dns-prod
    kind: ClusterIssuer
  dnsNames:
  - canary.33test.dev-sandbox.fpcomplete.com