apiVersion: v1
kind: Service
metadata:
  name: client-canary
  namespace: mcommerce
spec:
  selector:
    app: client
  ports:
    - port: 3001 
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-canary-deployment
  namespace: mcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: canary
  template:
    metadata:
      labels:
        app: client
        version: canary
    spec:
      containers:
        - name: client
          image: oakhmis/canary-image:latest  
          ports:
            - containerPort: 3001
              name: client-port
