apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-v2
  namespace: mcommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      version: v2
  template:
    metadata:
      labels:
        app: client
        version: v2
    spec:
      containers:
      - image: oakhmis/canary-image:latest
        imagePullPolicy: IfNotPresent
        name: tornado
        ports:
        - containerPort: 8888